### ISSUE TITLE
Don't Repeat Yourself

### ISSUE THREAD

**Issue by zannain** [DChan066/ColmarAcademy#5]
[Dont-Repeat-Yourself](http://deviq.com/don-t-repeat-yourself/). This is one of the most well-known programming principles. If you find yourself repeating certain styles this is an indication that you may be able to simplify your stylesheet by making use of classes or combining CSS selectors that will receive the same styles:

```css
h1 {
  font-size: 1.875rem;
  font-weight: 800;
}

h2 {
  font-size: 1.8rem;
  font-weight: 800;
}
```

instead:

```css
h1,
h2 {
  font-weight: 800;
}

h1 {
  font-size: 1.875rem;
}

h2 {
  font-size: 1.8rem;
}
```

This may not seem like a big deal but as you start working on larger web applications, combining selectors will save you a lot of time and really make a dent in your productivity and workflow.
